spring:
  application:
    name: booking-service
  data:
    mongodb:
      database: booking_service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: booking-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.phorest.booking.messaging
        spring.json.value.default.type: com.phorest.booking.messaging.ClientEventMessage
    properties:
      spring.json.add.type.headers: false

booking:
  kafka:
    topic:
      services: booking-services
      purchases: booking-purchases
    enabled: true
  csv:
    appointments-headers:
      - id
      - client_id
      - start_time
      - end_time
    services-headers:
      - id
      - appointment_id
      - name
      - price
      - loyalty_points
    purchases-headers:
      - id
      - appointment_id
      - name
      - price
      - loyalty_points

client:
  kafka:
    topic: client-events
    enabled: true

security:
  enabled: true
  jwt:
    secret: phorest2025-super-secret-key-change-me-please
    expiration: 3600
