spring:
  application:
    name: loyalty-service
  data:
    mongodb:
      database: loyalty_service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: loyalty-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.phorest.loyalty.messaging
    properties:
      spring.json.add.type.headers: false

client:
  kafka:
    topic: client-events
    enabled: true

booking:
  kafka:
    topic:
      services: booking-services
      purchases: booking-purchases
    enabled: true
