spring:
  application:
    name: loyalty-service
  data:
    mongodb:
      database: loyalty_service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: loyalty-service
      auto-offset-reset: earliest

client:
  kafka:
    topic: client-events
    enabled: true

booking:
  kafka:
    topic:
      services: booking-services
      purchases: booking-purchases
    enabled: true

security:
  enabled: true
  jwt:
    secret: phorest2025-super-secret-key-change-me-please
    expiration: 3600
