version: "3.9"

networks:
  phorest-network:
    driver: bridge

services:
  gateway-service:
    build:
      context: ..
      dockerfile: gateway-service/Dockerfile
    image: phorest/gateway-service:latest
    ports:
      - "8080:8080"
    networks:
      - phorest-network
